### ISSUE TITLE
Maturity Levels to About File Contents Alignment

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#209]
I think that the maturity levels of particular ontologies should be aligned withe contents of the about files, at least for all ontologies in [ISO](https://github.com/edmcouncil/idmp/tree/master/ISO) folder: an ontology has the idmp-chg:Release level iff it is imported in [AboutIDMPProd.rdf](https://github.com/edmcouncil/idmp/blob/master/AboutIDMPProd.rdf).

As an aside, @ElisaKendall could you review the import contents of [AboutIDMPProd.rdf](https://github.com/edmcouncil/idmp/blob/master/AboutIDMPProd.rdf), in particular with respect to CMNS and LCC ontologies?

**Comment by ElisaKendall** [comment]
This issue was closed via pull request #220
