### ISSUE TITLE
IDMP-138 - Extension of Registration Authorities

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/idmp#229]
A number of the existing registration authorities in the ontology called 'ISO 11238 Registration Authorities Ontology' are incomplete, and others are missing altogether.  This should be addressed, including confirmation that they are all complete from a hygiene perspective.

**Comment by mereolog** [comment]
@ElisaKendall this is now rather old - what shall we do about it?

**Comment by ElisaKendall** [comment]
Closed to the resolution of pull request #230
