### ISSUE TITLE
molecular structure is classified by optical activity is wrong 

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#241]
The molecular structure has no optical activity, so at best it is an indirect classification, by the substance that the molecular structure defines.

The substance, defined by the molecular structure can be classified by optical activity.

**Comment by ElisaKendall** [comment]
@tw-osthus Ok - I agree, but in Figure 19, in ISO 11238, optical activity is actually on Moiety, not on Substance.  That's the only place it occurs in that specification. In ISO 19844 it is on Structure, as is Stereochemistry, Molecular Formula and Molecular Formula by Moiety. This leads me to believe that the definition of structure in 19844 is incorrect, or that Structure is simply a collection of properties to make mapping to relational databases easier, but that it is not a semantic notion of structure.  We could change the way we model all this, but I want to make sure that Heiner, Matthias, and others agree.  Perhaps that should be on our topic list for Monday.

**Comment by ElisaKendall** [comment]
@tw-osthus The resolution to IDMP-391 moved the restriction from structure to chemical substance and to moiety, with annotations stating that we are not fully compliant with the ISO specification from a modeling perspective, so I think this has been addressed.
