### ISSUE TITLE
single substance has max 1 molecular structure is wrong

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#244]
We have defined: single substance has max 1 molecular structure

This is wrong in 2 ways:
A chemical can have more than one molecular structure, as the molecular structure depends on the granularity/precision/perspective of the molecular structure modeling the molecule. see for example
https://en.wikipedia.org/wiki/Resonance_(chemistry)

It is also not what the standard actually states.
The IDMP standard requires that a single substance can be **defined** by a single representation or set of descriptive element.

'single substance' subclass of **some** 'can be defined of a single representation...'

We cannot easily define "something that can be defined by a single representation or set of descriptive element" in the ontology as this is a meta expression about classes. 

We can add an annotation property "is fully defined by", but the reasoner would ignore it.
If we add an object property "is fully defined by" we have punning.

**Comment by tw-osthus** [comment]
Actually 
Amlodipine 'is fully defined' by 'Amlodipine molecular structure' 
would work in the current model.

but introducing the object property 'is fully defined by' as an instance level equivalent of owl:isEquivalentClass is the consequence.

We also have to introduced 'is partially defined by' as instance level equivalent to rdfs:subClassOf.

**Comment by ElisaKendall** [comment]
@chemantics Matthias, I know we are overdue for a conversation - would you please take a look at how this is done currently, and think about @tw-osthus suggestion, to make sure that whatever we do works across Chemantics and other repositories / representations?  We could create restrictions using equivalence / subclass relationships, but I want to make sure it is right and that the semantics don't cause implementation challenges at the same time.

**Comment by ElisaKendall** [comment]
This was addressed via pull request #280.
