### ISSUE TITLE
Identifiers (and possibly codes) for substances

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#256]
Per analogy to https://github.com/edmcouncil/idmp/issues/228 we could add an axiom like this one:
`ChemicalSubstance subClassOf isIdentifiedBy min 0 SubstanceIdentifier.`
to show that a chemical substance is typically identified by a substance identifier.

Similarly, for SubstanceCode.

**Comment by ElisaKendall** [comment]
@mereolog I think this is a problem - substances have many, many substance codes, and there is no internationally agreed substance identifier, which is how substance identifier is defined. The IDMP standard claims that there will be an ISO IDMP RA (registration authority) named to mint such identifiers, but it hasn't been done to date, nor has such a task been delegated to the relevant national medicines regulatory agencies, which I confirmed at the Boston meeting with the FDA. So I would not recommend adding these inferences. We can infer the relevant codes now, either through formal reasoning or inverse SPARQL queries, which is the right pattern given how these things are defined in the standards.

**Comment by ElisaKendall** [comment]
@mereolog maybe for substance code but not for substance identifier - there is no internationally minted identifier for substances  YET, and no registration authority (RA) assigned by ISO, so this might encourage wrong usage of substance identifier by pharma companies. As of this moment, there are only substance codes, and we do not want people to use substance identifier until such time as there is such a thing.
