### ISSUE TITLE
IDMP-352

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#265]
modelling of molecule and chemical structure
https://jira.edmcouncil.org/browse/IDMP-352

**Comment by mereolog** [comment]
This is now quite old.
@tw-osthus where are we with this?

**Comment by tw-osthus** [comment]
It is on hold, because depends on the resolution of the substance model.

**Comment by ElisaKendall** [comment]
@mereolog @tw-osthus Thomas and I agreed that this work is included in the Q1 2023 release, so we can close this issue.
