### ISSUE TITLE
idmp-sub:molecular graph is inconsistent

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#266]
the current definition / hierarchy of molecular graph is inconsistent.

def: single chemical structure that is an unambiguous representation of the arrangement of atoms, normalized to conform with the International Union of Pure and Applied Chemistry (IUPAC) specification for drawing chemical structures to the degree possible

 

It should be either a structure or a representation

If the molecular graph is a topological model of the connectiveness of the molecule then it should be a subclass of molecular structure. If it is a representation, then the definition must be changed.

**Comment by tw-osthus** [comment]
part of https://jira.edmcouncil.org/browse/IDMP-352

**Comment by ElisaKendall** [comment]
@tw-osthus This still needs some work - whether we keep it under IDMP-352 or make it standalone. It wasn't addressed under #273, and depending on the changes we make then the restriction with respect to SMILES might need to move from molecular structure to something else, possibly to substance.

**Comment by ElisaKendall** [comment]
@tw-osthus I think this has now been addressed via pull request #243.
