### ISSUE TITLE
cmns-qtu:DimensionlessQuantity and sibling classes are inconsistent

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#268]
based on its definition it is a quantity, but it is subclassed under quantity kind.

The definitions of base quantity kind and derived quantity kind are also about quantities not quantity kinds.

A quantity kind is 
an aspect common to mutually comparable quantities
which I read as classifier of quantities.

A classifier is not the same as the thing it classifies, although that is a common error when defining ontologies.

**Comment by mereolog** [comment]
@tw-osthus this is now quite old - what shall we do about it?

**Comment by tw-osthus** [comment]
The issue is still not fixed.
