### ISSUE TITLE
hasSimplifiedMolecularInputLineEntrySpecification is misleading and inconsistent

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#278]
the label is very long and chemists would prefer to use the abbreviation "has SIMLES" instead. 

SMILES is an acronym of  "Simplified Molecular Input Line Entry Specification", but few people will know, recognize or remember this.
We have  'idmp-dtp:has XML-encoded data', instead of 'idmp-dt:has extensible markup language encoded data', so using the well known acronym is already in the ontology.

cmns-av:abbreviation "SMILES" should be replaced with cmns-av:acronym

but the definition of the relation is also not semantically correct: 

> specification for an unambiguous linear representation of chemical or molecular structures using ASCII characters

This is a definition of SMILES specification not of the relation between the molecular structure and the SMILES representation of it.

The relation between the molecular structure and its representation as a text string in SMILES format should be:
has SMILES representation
or abbreviated: has SMILES

We might want to change this to an object property 'has structure representation'
_:ethanole 'has structure representation' [
       a 'structure representation'
       'has specification/format' SMILES
       'has text value' 'CCOH'
]
with SMILES representation as structure representation following SMILES.

or define SMILES representation as subclass of structure representation
and then
'has SMILES representation' range 'SMILES representation'
'has SMILES value' = 'has SMILES representation' o 'has text value' if we want to have shortcuts and have a datatype property.

This allows SYBYL and Wiswesser Line Notation mentioned in the notes also easily added, in fact all text based (non binary) representations, for example the MOL format mentioned in the standard can be represented in the same way.

@ElisaKendall there is probably already an existing pattern in commons.

**Comment by ElisaKendall** [comment]
We might want to also have two properties - one with respect to a canonical SMILES and one that is not necessarily in a canonical format. But at a minimum the approach that includes both a subclass and short-cut value seems appropriate.  Ensuring that people can use the SMILES for look-up / query purposes is useful.

**Comment by tw-osthus** [comment]
Still open, I have not worked on it.
