### ISSUE TITLE
Range of https://www.omg.org/spec/Commons/TextDatatype/hasTextValue

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#283]
What is the range of https://www.omg.org/spec/Commons/TextDatatype/hasTextValue property?

When this property is used for instances, it is used as if its range datatype were strings.
But when it is used in restrictions, e.g., in https://github.com/edmcouncil/idmp/blob/516ca6b3e71a5265b94f3150d808f4ac5f3131e5/CMNS/Designators.rdf#L45-L50.

**Comment by ElisaKendall** [comment]
The Text datatype is defined specifically to enable the range of that property to be in the union of xsd:string and rdf:langString. It is a work-around for the schizophrenia between RDF 1.1 and OWL 2, where each language has defined odd differences between plain literals and those that are typed, where only plain literals can be language tagged.  This isn't an issue - it's a feature :). For the purposes of conversion to SHACL, use xsd:string in the place of Text, unless the content is language tagged. We don't have any cases of rdf:langString that I am aware of in IDMP ... yet ... but I'm sure we will.
