### ISSUE TITLE
TTL files not loading into Protege

### ISSUE THREAD

**Issue by janelomax** [edmcouncil/idmp#291]
These TTL files from https://spec.edmcouncil.org/idmp/page/owl won't load into Protege correctly:

<img width="1513" alt="Screenshot 2023-01-19 at 17 59 14" src="https://user-images.githubusercontent.com/6639811/213523607-4e9f20f6-6420-4f61-be80-e5083644a7cd.png">

Prod has no classes (or any content) and for Dev it complains about missing imports. The Quickstart files load okay.

**Comment by mereolog** [comment]
@janelomax thanks for the feedback.

As for empty Load Prod files, this looks like an issue in our publication process - we will look into asap.
As for missing imports, as far as I can all of them refer to OMG Common ontologies. As of now, most of them do not resolve, so execution of import statements fail. We have no governance over them, so we cannot even redirect such calls. @ElisaKendall may fill more details.

**Comment by janelomax** [comment]
Hi - the LoadProd file now seems to have content so that bit worked! It still won't load into Protege because of the broken imports though:

![Screenshot 2023-02-06 at 16 53 16](https://user-images.githubusercontent.com/6639811/217034789-9f2cfcac-659f-4320-a581-6288c09cb078.png)

that URI looks like one in your domain?

**Comment by mereolog** [comment]
> Hi - the LoadProd file now seems to have content so that bit worked! It still won't load into Protege because of the broken imports though:
> 
> ![Screenshot 2023-02-06 at 16 53 16](https://user-images.githubusercontent.com/6639811/217034789-9f2cfcac-659f-4320-a581-6288c09cb078.png)
> 
> that URI looks like one in your domain?

Yes, it is indeed.

Funny enough, I didn't get this error when I opened the file today - "it works on my machine ..." :)
Is this the only missing import from the Pistoia domain?
What happens why you try to open https://spec.pistoiaalliance.org/idmp/ontology/master/latest/ISO/ISO11240-UnitsOfMeasurement.rdf in the browser? And what about https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11240-UnitsOfMeasurement.rdf
We can send you some command-line scripts to investigate further - perhaps some firewall issues are at stake here.

CC: @przemekgradzki
