### ISSUE TITLE
Competency questions for GSRS

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#305]
The [current competency questions](https://github.com/edmcouncil/idmp/tree/master/etc/CQ/GSRS) do not work, i.e., return empty result sets, for the [latest release of GSRS Transformation](https://pistoiaalliance.dev.accurids.com/dataset/details/GSRS) - see: https://data.world/edm-council/idmp-gsrs-transformation/workspace. We need to update them.

**Comment by aliariff** [comment]
Hi @mereolog 

Which CQ exactly do you use? Because the link `current competency questions` that you provided is incorrect.

Also, I don't have access to the data.world website.

**Comment by mereolog** [comment]
> Hi @mereolog
> 
> Which CQ exactly do you use? Because the link `current competency questions` that you provided is incorrect.
> 
> Also, I don't have access to the data.world website.

The link is fixed.

As for data.world, the project is public, so anyone who has account there should access it.
Otherwise, you need to run the queries in your local triple store.

**Comment by mereolog** [comment]
As a matter of fact, if you add the IDMP ontology to the GSRS dataset, only cq2 does now work.

**Comment by mereolog** [comment]
cq4 produces two identical rows - perhaps we should add the 'DISTINCT' qualifier?

**Comment by mereolog** [comment]
cq4-1 produces a result with an empty authorityLabel.
@ElisaKendall , @Heiner-Oberkampf  is this correct?
