### ISSUE TITLE
Obsolete triples in GSRS transformed data

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#308]
There are more than 1000 triples of the form:
IRI skos:related IRI.
See: 
[reflexive_skos_related.csv](https://github.com/edmcouncil/idmp/files/10847991/reflexive_skos_related.csv)

For instance, 
`https://gsrs.ncats.nih.gov/api/v1/substances/NY22HMQ4BX skos:related https://gsrs.ncats.nih.gov/api/v1/substances/NY22HMQ4BX`

IMHO they are totally obsolete as they convey hardly ever meaning. I would recommend we get rid of them.

**Comment by Heiner-Oberkampf** [comment]
@aliariff  please use skos:related for the fall-back property only for cases where Subject and Object are different IRIs
