### ISSUE TITLE
Ontology StructuredCollections.rdf

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#346]
What is the status of https://www.omg.org/spec/Commons/StructuredCollections/?

It is registered in https://www.omg.org/spec/Commons/MetadataCMNS/ and in CMNS/catalog-v001.xml, but not in AboutIDMPDev-ReferenceIndividuals.rdf or catalog-v001.xml, so the IDMP viewer throws a 404 when someones tries to display it:

![image](https://user-images.githubusercontent.com/11171688/235115463-29f94052-d395-4cf8-a5b6-d08291f4f23f.png)

**Comment by ElisaKendall** [comment]
@mereolog Ok - I'll fix that -- there are more changes coming based on a discussion I had with Thomas, but will fix this in the context of making those changes this coming week

**Comment by ElisaKendall** [comment]
@mereolog The resolution to this issue was fixed via pull request #349.
