### ISSUE TITLE
Obsolete or forgotten patterns - cmns-pts:isManifestedIn

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#382]
We require that an [ingredient](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Ingredient) [is manifested in](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FPartiesAndSituations%2FisManifestedIn) some [manufactured item](https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/ManufacturedItem) - see: https://github.com/edmcouncil/idmp/blob/487882fcdbacf78b74aa1c3c415da9af8e189c0a/ISO/ISO11615-MedicinalProducts.rdf#L234-L239.

As of [487882f](https://github.com/edmcouncil/idmp/commit/487882fcdbacf78b74aa1c3c415da9af8e189c0a) there are 39 (direct or indirect) instances of [ingredient](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Ingredient) and none of these is manifested in anything.

I take that this may mean that 

1. either the above cmns-pts:isManifestedIn pattern was dropped/replaced, in which case we should remove/adapt the respective restriction;
2. or that the pattern was forgotten in hand-crafting the examples, in which case the examples should be amended.

**Comment by ElisaKendall** [comment]
@mereolog Updates with respect to manufactured item and the relationships including isManifestedIn will be made as we update the patterns in Confluence over the coming week or two - these have not been forgotten, but the updates were deferred until we had completed the changes needed for ingredient roles, reference strength, and basis of strength with respect to jurisdiction, which are under review now.

**Comment by mereolog** [comment]
The class level has changed a little, but the issue still remains: no instance of [ingredient](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Ingredient) [is manifested in](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FPartiesAndSituations%2FisManifestedIn) anything.

https://github.com/edmcouncil/idmp/blob/50e149553f41271ffedd00c2cb7920b05630b07f/ISO/ISO11615-MedicinalProducts.rdf#L206-L218

**Comment by ElisaKendall** [comment]
@mereolog This is no longer the case, if you look at the Amlodipine example. Please confirm and close this with no change, thanks!
