### ISSUE TITLE
Obsolete or forgotten patterns - product roles played by products

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#383]
We require that any [product role](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/ProductRole) [is played by](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FPartiesAndSituations%2FisPlayedBy) some [product](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FProductsAndServices%2FProduct) - see:
https://github.com/edmcouncil/idmp/blob/487882fcdbacf78b74aa1c3c415da9af8e189c0a/ISO/ISO11615-MedicinalProducts.rdf#L2087-L2092 

As of [487882f](https://github.com/edmcouncil/idmp/commit/487882fcdbacf78b74aa1c3c415da9af8e189c0a) there are 11 (direct or indirect) instances of [product role](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/ProductRole) and none of these is [is played by](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FPartiesAndSituations%2FisPlayedBy) a [product](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FProductsAndServices%2FProduct) .

I take that this means that

1. either the above pattern was dropped/replaced, in which case we should remove/adapt the respective restriction;
2. or that the pattern was forgotten in hand-crafting the examples, in which case the examples should be amended.

I take that this may be a left-over from the change from products to product specifications.

**Comment by ElisaKendall** [comment]
@merelog This pattern has not been forgotten, and will be used as we build out relationships to medicinal product over the coming weeks. Some restrictions may be relaxed depending on what we find in the related example data, but the pattern is needed per discussion in the ontology calls.

**Comment by ElisaKendall** [comment]
@merelog - Please recheck this now that we've augmented the restriction to include ProductSpecification via IDMP-633, which was merged on Aug 3rd (yesterday).

**Comment by mereolog** [comment]
This is not an issue any more.
