### ISSUE TITLE
Legal punning in d9ececf commit in master

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#387]
[d9ececf](https://github.com/edmcouncil/idmp/commit/d9ececfd713d3f42f60b83094267a08a4f64a45a) has four owl:Classes that are used as owl:NameIndividuals:

https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/ModificationMethodType-Physical
https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/ModificationMethodType-Structural
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/MedDRA-AnginaPectoris
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/MedDRA-Hypertension

Although this is technically correct, we may want review them to make sure that the punning was intended.

This issue relates to #386.

**Comment by ElisaKendall** [comment]
The two issues related to the Amlodipine example were addressed in IDMP-581, #386
