### ISSUE TITLE
IDMP-597 Revise therapeutic indication text

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#396]
see https://jira.edmcouncil.org/browse/IDMP-597

hasIndicationText an OWL ObjectProperty with range Document
update the Amlodipine Example and SPARQL query to adopt to this change:
hasIndicationText -> hasIndicationText/hasTextValue
add Roche example for CellCept with 3 medical conditions (prophylaxes) and single indication text.

**Comment by ElisaKendall** [comment]
Closed to the merge of pull request #397
