### ISSUE TITLE
Possible mistype exemplary individuals

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#399]
As of [3a3e673](https://github.com/edmcouncil/idmp/commit/3a3e6732a6e0aa68003fcf2306803cf4313d3101) there are several exemplary individuals whose type(s) may be wrong - see:  [possibly_mistyped_individuals.xlsx](https://github.com/edmcouncil/idmp/files/11884348/possibly_mistyped_individuals.xlsx)

Consider the first row from this table.
Because of the logical constraints on its type [AmlodipineBesylateAsActiveIngredientInNorvasc](https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylateAsActiveIngredientInNorvasc) should be linked (via [hasReferenceStrength](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/hasReferenceStrength)) to an instance of [ReferenceStrength](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/ReferenceStrength). Actually it is linked to an instance of  [MassBasedStrength](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/MassBasedStrength), which is not a subclass of [ReferenceStrength](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/ReferenceStrength).  This _may_ imply that the latter instance has the wrong type or that the proper instance of [ReferenceStrength](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/ReferenceStrength) is missing or that the pattern changed at the class level.

**Comment by ElisaKendall** [comment]
@merelog - as of today (7/13), the cases you've identified for strength in the Amlodipin and Terlipressin examples have been addressed in updates to those examples. I'm not convinced that being of a more specific type, such as being of type MedicinalProduct in cases where the requirement is for some kind of product is an issue. There are a few others that still require investigation, however. These include cases such as where the actual value is an authorized medicinal product but according to the ontology should be medicinal product, or is active ingredient and should be substance (role vs. specification), which I'm surprised didn't cause an inconsistency. If you ran a query to find these, would it be possible to re-run it and see what  you get now that the examples have been updated? I'm not expecting the clinical trial issues to be resolved, but possibly some in the Amlodipine and Terlipressin examples. And please exclude cases where they type is that of a direct subclass of the expected type.  We might consider that a new test if we can exclude cases that are more specific, such as medicinal product where product was expected.

**Comment by mereolog** [comment]
> @merelog - as of today (7/13), the cases you've identified for strength in the Amlodipin and Terlipressin examples have been addressed in updates to those examples. I'm not convinced that being of a more specific type, such as being of type MedicinalProduct in cases where the requirement is for some kind of product is an issue. There are a few others that still require investigation, however. These include cases such as where the actual value is an authorized medicinal product but according to the ontology should be medicinal product, or is active ingredient and should be substance (role vs. specification), which I'm surprised didn't cause an inconsistency. If you ran a query to find these, would it be possible to re-run it and see what you get now that the examples have been updated? I'm not expecting the clinical trial issues to be resolved, but possibly some in the Amlodipine and Terlipressin examples. And please exclude cases where they type is that of a direct subclass of the expected type. We might consider that a new test if we can exclude cases that are more specific, such as medicinal product where product was expected.

I ran a [different, more accurate, query](https://data.world/edm-council/idmp-ontology/workspace/query?queryid=6f1060ce-5172-4b42-a162-77334a4e0d49) this time and got more issues.

[possibly_mistyped_individuals_new_785e1fe.xlsx](https://github.com/edmcouncil/idmp/files/12050469/possibly_mistyped_individuals_new_785e1fe.xlsx)

I eyeballed a few of them and all I checked are genuine issues.
