### ISSUE TITLE
fix parameter comment in UC1-CQ3.1

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#413]
`# Example for Terlipressin: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetateSUN>
`
should be
`# Example for Terlipressin: <https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetateSUN-PharmaceuticalProduct>`

**Comment by mereolog** [comment]
This is addressed in https://github.com/edmcouncil/idmp/pull/408.
