### ISSUE TITLE
IDMP-615 Therapeutic Indication CQ2: SPARQL Query

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#419]
https://jira.edmcouncil.org/browse/IDMP-615

make SPARQL query for

What ingredient role (excipient, ...) played by a substance \<S> is part of what (authorized, investigational) medicinal product that has a therapeutic indication indicated by a MedDRA ID \<I>?

**Comment by tw-osthus** [comment]
depends on IDMP-597

**Comment by ElisaKendall** [comment]
This issue is closed to the resolution of #420
