### ISSUE TITLE
Two properties that are required for code elements and classifiers should be excluded from tests for incomplete examples

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/idmp#432]
Two of the properties of code elements and classifiers result in false positives in testing for incomplete examples. These include: (1) cmns-cls:classifies and (2) cmns-dsg:denotes. Many of our controlled vocabularies will be used for classification of content in data sets that pharma companies may have internally, or that are publicly available. We will not have examples of every classifier or code element in the standards themselves, however. 

These two properties should be excluded from the test.

**Comment by ElisaKendall** [comment]
Note that I've changed many of the restrictions  to use allValuesFrom rather than someValuesFrom for the time being, which eliminates some of the warnings, but that may not reflect all of the required semantics, depending on the classifier or code element.

**Comment by mereolog** [comment]
@ElisaKendall can we resolve https://github.com/edmcouncil/idmp/issues/505 first?

**Comment by ElisaKendall** [comment]
> @ElisaKendall can we resolve #505 first?

I've attempted to respond to your questions on that one, but let me know if it makes sense to you. I think there are a limited number of cases where it is ok to be incomplete - the SI system of units and system of quantities issue will be resolved when we generate the library from SysML v2, for example, so the warning doesn't bother me. I'll take a look at others and attempt to clarify which cases should be ignored.  We should not ignore any completeness warnings for some examples, such as Amlodipine or Terlipressin, which are intended to be complete, though - only for some of the other "more demonstration-like" cases, such as the Qlaira example. I am thinking that these need a different status other than provisional or informative, maybe demonstration? So that we still enforce some of the tests but not all of them?

**Comment by ElisaKendall** [comment]
@mereolog #505 has been resolved - this will become even higher priority for the 1.0 release as we fill out values that we know from some of the details in the standards. For example, there are 3 new instances of classifier in the substances ontology which classify mixtures (see pull request for IDMP-675) and now there are warnings that these individuals are incomplete. They are not - we need the data in order to make them complete, which will be on the pharma side or possibly in GSRS.

**Comment by mereolog** [comment]
@ElisaKendall where are we with this?
