### ISSUE TITLE
cmns-ra:designates is equivalent to cmns-ra:isDesignatedBy

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#434]
cmns-ra:designates is equivalent to cmns-ra:isDesignatedBy - see the snip below.

![image](https://github.com/edmcouncil/idmp/assets/11171688/617ac781-66f2-4278-945b-bd9e4fc79795)

The reason for this is that:
1. cmns-ra:isDesignatedBy is an inverse of cmns-ra:designates
2. cmns-ra:designates is symmetrical

I think that 2 is wrong.

**Comment by ElisaKendall** [comment]
The resolution to this issue was merged via pull request #435
