### ISSUE TITLE
cmns-qtu:QuantityKind and cmns-dsg:isDefinedIn property

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#440]
Since cmns-qtu:QuantityKind inherits from cmns-cls:Classifier, all its instances must be related by cmns-dsg:isDefinedIn to some instances of cmns-cls:ClassificationScheme.

As of [a2a9596](https://github.com/edmcouncil/idmp/commit/a2a95960d65df045be25c66c51dd706836531609), there are 5 that are not: they are cmns-dsg:isDefinedIn idmp-ucum:UnifiedCodeForUnitsOfMeasure, which is not an (explicit or implicit) instance of cmns-cls:ClassificationScheme - see below:

resource | property | object | requiredType | actualType
-- | -- | -- | -- | --
idmp-ucum:AmountOfSubstance | cmns-des:isDefinedIn | idmp-ucum:UnifiedCodeForUnitsOfMeasure | cmns-cls:ClassificationScheme | idmp-uom:UnitOfMeasureIdentificationScheme
idmp-ucum:Length | cmns-des:isDefinedIn | idmp-ucum:UnifiedCodeForUnitsOfMeasure | cmns-cls:ClassificationScheme | idmp-uom:UnitOfMeasureIdentificationScheme
idmp-ucum:Mass | cmns-des:isDefinedIn | idmp-ucum:UnifiedCodeForUnitsOfMeasure | cmns-cls:ClassificationScheme | idmp-uom:UnitOfMeasureIdentificationScheme
idmp-ucum:MolarMass | cmns-des:isDefinedIn | idmp-ucum:UnifiedCodeForUnitsOfMeasure | cmns-cls:ClassificationScheme | idmp-uom:UnitOfMeasureIdentificationScheme
idmp-ucum:Volume | cmns-des:isDefinedIn | idmp-ucum:UnifiedCodeForUnitsOfMeasure | cmns-cls:ClassificationScheme | idmp-uom:UnitOfMeasureIdentificationScheme

**Comment by tw-osthus** [comment]
ucum:UnifiedCodeForUnitsOfMeasure (UCUM) can be both
a uom:UnitOfMeasureIdentificationScheme and a cls:ClassificationScheme

I do not know whether UCUM also contains quantity kinds besides units of measures. Quantity kinds are classifiers for quantities (or maybe units of measure).

If UCUM contains quantity kinds, then nothing is wrong.
