### ISSUE TITLE
idmp-spor:hasSPORTermDescription is language dependent

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#465]
spor:hasSPORTermDescription is currently a datatype property, a subproperty of cmns-txt:hasTextValue but in the SPOR XSD schema it is a translated string

see the mapping table in https://wiki.edmcouncil.org/display/IDMP/Pattern%3A+Representing+Controlled+Vocabularies+for+EMA+SPOR+Referentials
or the attached XSD schema

As cmns-txt:hasTextValue expects xsd:string this cannot be mapped to rdf:langString so it has to be an object property referring to the description which can have a language string or assigned a lcc-lr language.

Alternatively we should have a cmns-txt:hasLangStringValue to make it a literal.

**Comment by ElisaKendall** [comment]
This issue should be closed to the resolution of pull request #466
