### ISSUE TITLE
AboutIDMPDev-ReferenceIndividuals.rdf alignment with AboutIDMPDev.rdf

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#473]
Since hygiene tests are run over ontologies "registered" in AboutIDMPDev-ReferenceIndividuals.rdf, all ontologies that are "registered" in AboutIDMPDev.rdf should be also "registered" in AboutIDMPDev-ReferenceIndividuals.rdf - otherwise those that are not will not be tested.

**Comment by ElisaKendall** [comment]
@mereolog I thought that this had been addressed but I can see that there is still something different when I load the ontologies using AboutIDMPDev in the UI in Protege - not all prefixes are properly applied, so ...

**Comment by mereolog** [comment]
> @mereolog I thought that this had been addressed but I can see that there is still something different when I load the ontologies using AboutIDMPDev in the UI in Protege - not all prefixes are properly applied, so ...

Could you give an example or two?

**Comment by ElisaKendall** [comment]
This has been addressed via pull request #491
