### ISSUE TITLE
IDMP-632 - Batch should be a subclass of Constituent rather than Product

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/idmp#485]
A batch is a constituent of a product, not a product in its own right. This should be corrected in the ontology. The same is true of Lot. A lot should be a subclass of constituent rather than product.

**Comment by tw-osthus** [comment]
I am not so sure. It is more a collection then a constituent. A batch is a collection of goods produced at the same time. The same is lot, which is a collection of goods sold as one item.

In chemistry, it is important to distinguish between batch production and continuous production. If we define product as material that is being produced (so not necessary sold which is good), then subclassing from product is correct.

**Comment by ElisaKendall** [comment]
@tw-osthus I'm not sure who raised this in one of our Monday meetings - it was one of the pharma companies I think. I've asked Johnson & Johnson how they represent it - we can confirm the approach on Monday next week before we finalize the release.

**Comment by ElisaKendall** [comment]
This has been merged via pull request #486
