### ISSUE TITLE
Non-classifying, but just denoting, classifiers

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#505]
There are four classifiers that only denote things without classifying them - shouldn't they?

classifier | thing
-- | --
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/P015011211 | https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/NorvascPackagedMedicinalProduct
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-1x28Box-SKU | https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-1x28Box-PackagedMedicinalProduct
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-3x28Box-SKU | https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-3x28Box-PackagedMedicinalProduct
https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-6x28Box-SKU | https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-6x28Box-PackagedMedicinalProduct

**Comment by tw-osthus** [comment]
The SKU denotes the PackagedMedicinalProduct which is a product specification, not a physical product. The SKU is specific for this product specification, not a class of product specifications, so denotes is correct. If the SKU denotes something broader then what is specified in the product specification, then yes classifies would be more correct. Maybe we can use both in this case.

From: Pawel Garbacz ***@***.***>
Sent: Donnerstag, 12. Oktober 2023 15:19
To: edmcouncil/idmp ***@***.***>
Cc: Thomas Weber ***@***.***>; Assign ***@***.***>
Subject: [edmcouncil/idmp] Non-classifying, but just denoting, classifiers (Issue #505)


CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




There are four classifiers that only denote things without classifying them - shouldn't they?
classifier

thing

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/P015011211

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/NorvascPackagedMedicinalProduct

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-1x28Box-SKU

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-1x28Box-PackagedMedicinalProduct

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-3x28Box-SKU

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-3x28Box-PackagedMedicinalProduct

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-6x28Box-SKU

https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/QlairaExample/Qlaira-6x28Box-PackagedMedicinalProduct

**Comment by ElisaKendall** [comment]
@mereolog @tw-osthus I agree with both of you, depending on the case - not all designations (code elements, names, identifiers, etc.) are classifiers - only some of them are both designations and classifiers. 

A stock keeping unit (SKU), however, is a designation and classifier for a product (i.e., for all products that have certain characteristics in common, typically all characteristics, including size, color, components, etc., aside from an individual serial number). The examples include 4 individuals that are of type SKU, as shown above. Each of these denotes some class of products that share the same product specification.  So you could say that the SKU denotes the product specification and classifies the products that share / conform to that specification. Does that make sense?

**Comment by mereolog** [comment]
I am happy with these four things both denote and classify.

**Comment by ElisaKendall** [comment]
The resolution to this issue was merged via pull request #514
