### ISSUE TITLE
Can't load dependencies in example

### ISSUE THREAD

**Issue by FPRM** [edmcouncil/idmp#507]
Tried on Tag master_v0.5.0 and also on branch master.
I tryed to load the exemple file "AmlodipineExemple.rdf", and a lot of structure dependencies are broken because it points to a 404 page
(happens on omg.org rdf dependencies and also on https://spec.pistoiaalliance.org  dependencies)

As full depencies are inside the repositories i suggest to modify the link of the decencies from web sources to relative file pointing

**Comment by ElisaKendall** [comment]
@FPRM Hi Florian, we do include relative catalog files at the top level in the idmp GitHub and in the ISO folder, just not in the examples folder. So if you have cloned the repository, to see the examples you can open AboutIDMPDev-ReferenceIndividuals.rdf in the top-level repository using Protege, and all of the dependencies will be resolved.

I hope that helps,

Elisa
