### ISSUE TITLE
Satisfiability of AboutIDMPDev-ReferenceIndividuals.rdf

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#515]
I am not able to check the satisfiability of all classes in [babe718](https://github.com/edmcouncil/idmp/commit/babe71829d8ddcd866ac263c9e709a5e2fbd34d0), i.e., running Pellet in Protege takes much longer than usual, i.e., > 15 minutes.

**Comment by ElisaKendall** [comment]
@mereolog It took just over 14 minutes on my laptop with other things running at the time, FYI. I don't know that this is significantly longer than I've seen recently, but happy to help investigate.
