### ISSUE TITLE
Punning of hasSPORTermDescription

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#525]
idmp-spor:hasSPORTermDescription is declared as a datatype property:

https://github.com/edmcouncil/idmp/blob/780de13b140dd3af68ea63d4c87804bc72a724ca/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf#L1532-L1537

but is used as an object property, e.g., its range is declared as an OWL class and its superproperty is an object property. 
See also below:

https://github.com/edmcouncil/idmp/blob/780de13b140dd3af68ea63d4c87804bc72a724ca/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf#L1269-L1274

So we have an instance of illegal punning here.

I think idmp-spor:hasSPORTermDescription should be re-declared as an object property.

**Comment by tw-osthus** [comment]
It should be an ObjectProperty.

**Comment by ElisaKendall** [comment]
This issue was resolved via pull request #526
