### ISSUE TITLE
Textual values for substance names

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#564]
A [substance name](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/SubstanceName) is required to have, two, _possibly_ different, textual values:
1. https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/hasSubstanceNameValue exactly 1 [string](http://www.w3.org/2001/XMLSchema%23string)
1. https://www.omg.org/spec/MVF/MultipleVocabularyFacility/hasTextualName exactly 1 [string](http://www.w3.org/2001/XMLSchema%23string)
     - this one is inherited from https://www.omg.org/spec/MVF/MultipleVocabularyFacility/MVFElement.

Note that https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/hasSubstanceNameValue has parent: https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/hasTextualName. 

So:
- **if** https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/hasSubstanceNameValue **had** https://www.omg.org/spec/MVF/MultipleVocabularyFacility/hasTextualName as its parent
or
- **if** https://www.omg.org/spec/MVF/MultipleVocabularyFacility/MVFElement **used** https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/hasTextualName

then the possibility of this discrepancy would disappear.

**Comment by tw-osthus** [comment]
@ElisaKendall there is a label conflict between MVC and LCC concerning "has textual name"

Many of our substance name instances are instances of MVFElements which introduces his problem.

We could make hasSubstanceNameValue a subproperty of both. Neither lcc:hasTextualName nor mvf:hasTextualName define a domain, so that should work.

However the real fix should be within the OMG ontologies where MVF should be harmonized with LCC.

**Comment by ElisaKendall** [comment]
@tw-osthus LCC will be revised to remove the duplication over the coming months, so we should standardize on the MVF property. I'll do a search and revise any that use LCC via this issue.

**Comment by mereolog** [comment]
@ElisaKendall can we close this now?

**Comment by ElisaKendall** [comment]
@mereolog I think so, unless you've found another discrepancy

**Comment by ElisaKendall** [comment]
The resolution of this issue was completed via pull request #566
