### ISSUE TITLE
Two typos in reference to rdfs:subPropertyOf

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#567]
In Medicinal Products ontology there are two typos in reference to rdfs:subPropertyOf:

https://github.com/edmcouncil/idmp/blob/f53c894444748b1f1baf3f81f2aaaeb1600a21a8/ISO/ISO11615-MedicinalProducts.rdf#L5714

https://github.com/edmcouncil/idmp/blob/f53c894444748b1f1baf3f81f2aaaeb1600a21a8/ISO/ISO11615-MedicinalProducts.rdf#L5723

**Comment by ElisaKendall** [comment]
This issue was resolved to pull request #568
