### ISSUE TITLE
Possibly obsolete triples with inverse properties

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#576]
As of [f210bb0](https://github.com/edmcouncil/idmp/commit/f210bb016f82fcac83485812b2b2f643f892c871) IDMPO contains almost 300 triples that fall under the schema given by this SPARQL query:

```
SELECT DISTINCT *
WHERE
{
    ?resource1 ?predicate ?resource2.
    ?predicate owl:inverseOf ?inversePredicate.
    ?resource2 ?inversePredicate ?resource1.
}
ORDER BY ?predicate ?resource1 ?resource2
```

The full list can be accessed here: 
[possible_obsolete_triples_with_inverse_properties.xlsx](https://github.com/edmcouncil/idmp/files/14981091/possible_obsolete_triples_with_inverse_properties.xlsx)

Given our problems with reasoning performance we may want to review them to verify that all of them are indeed needed as examples of the class-level descriptions.

**Comment by tw-osthus** [comment]
The reasoner must infer the inverted properties anyway. So I expect that an explicit assertion should not have an impact on reasoning performance.

Not asserting them explicitly may lead to some hygiene test warnings.



________________________________
Von: Pawel Garbacz ***@***.***>
Gesendet: Montag, 15. April 2024 17:27
An: edmcouncil/idmp ***@***.***>
Cc: Thomas Weber ***@***.***>; Assign ***@***.***>
Betreff: [edmcouncil/idmp] Possibly obsolete triples with inverse properties (Issue #576)


As of f210bb0<https://github.com/edmcouncil/idmp/commit/f210bb016f82fcac83485812b2b2f643f892c871> IDMPO contains almost 300 triples that fall under the schema given by this SPARQL query:

SELECT DISTINCT *
WHERE
{
    ?resource1 ?predicate ?resource2.
    ?predicate owl:inverseOf ?inversePredicate.
    ?resource2 ?inversePredicate ?resource1.
}
ORDER BY ?predicate ?resource1 ?resource2


The full list can be accessed here:
possible_obsolete_triples_with_inverse_properties.xlsx<https://github.com/edmcouncil/idmp/files/14981091/possible_obsolete_triples_with_inverse_properties.xlsx>

Given our problems with reasoning performance we may want to review them to verify that all of them are indeed needed as examples of the class-level descriptions.
