### ISSUE TITLE
Potentially vicious "circular" restrictions

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#577]
As of [f210bb0](https://github.com/edmcouncil/idmp/commit/f210bb016f82fcac83485812b2b2f643f892c871) IDMPO contains 17 OWL restrictions patterns like the one below:
- [SPOR data classification](https://spec.pistoiaalliance.org/idmp/ontology/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials/SPOR-DataClassification) rdfs:subClassOf [SPORControlledVocabularyTerm](https://spec.pistoiaalliance.org/idmp/ontology/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials/SPORControlledVocabularyTerm) 
- [SPORControlledVocabularyTerm](https://spec.pistoiaalliance.org/idmp/ontology/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials/SPORControlledVocabularyTerm) [has SPOR visibility](https://spec.edmcouncil.org/idmp/ontology/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials/hasSPORVisibility) exactly 1 [SPOR data classification](https://spec.edmcouncil.org/idmp/ontology/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials/SPOR-DataClassification)

[see: [possibly_vicous_circular_restrictions.xlsx](https://github.com/edmcouncil/idmp/files/14981380/possibly_vicous_circular_restrictions.xlsx)]

Since such circularity may "confuse" a reasoner and given our problems with reasoning performance we may want to review them to verify that all of them correspond to an adequate conceptualisation of the domain.

**Comment by tw-osthus** [comment]
It is correct. The visibility classification of SPOR terms is done by means of SPOR terms

I do not know how to help the reasoner here.

**Comment by tw-osthus** [comment]
I have tested a minimal ontology with this pattern and both Hermit and Pellet do not have a problem with it (3 classes, 4 individuals). Maybe it does not scale well. Cardinality restrictions are hard to reason.

**Comment by ElisaKendall** [comment]
@mereolog I've eliminated 4 of the 6 instances of "circular" restrictions in the Commons quantities and units ontology so far. The other two, and the one in MVF, are definitional and need to stay.  Still investigating the others, other than the SPOR restrictions, which as @tw-osthus mentioned, are definitional.

**Comment by ElisaKendall** [comment]
The changes we've agreed to make in the context of this issue were merged via pull request #600
