### ISSUE TITLE
Possible ill-formed definition for MarketingStatusReasonCode

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#583]
The definition for [MarketingStatusReasonCode](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11615-MedicinalProducts/MarketingStatusReasonCode) reads _sequence of characters denoting the reason for a legal action taken on the marketing or on the marketing authorisation can be specified using an appropriate controlled vocabulary_

I feel something odd about it and GPT4-turbo agrees - 'The sentence you provided is a bit awkward and somewhat unclear in structure. '

**Comment by ElisaKendall** [comment]
This issue has been addressed via pull request #596
