### ISSUE TITLE
Possibly broken URLs in IDMP Prod literals

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#594]
There are 7 broken URLs in IDMP Prod literals (as of [548f0e0](https://github.com/edmcouncil/idmp/commit/548f0e0f7afc3f9836c36b1cbc939ca8d3f384de))

[idmp_prod_possibly_broken_urls_548f0e0.xlsx](https://github.com/edmcouncil/idmp/files/15294220/idmp_prod_possibly_broken_urls_548f0e0.xlsx)

The check improves the one from https://github.com/edmcouncil/idmp/issues/587.

**Comment by ElisaKendall** [comment]
This issue was addressed via pull request #595
