### ISSUE TITLE
Obsolete restriction on idmp-sub:Amount

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#598]
https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Amount has an obsolete restriction:

https://github.com/edmcouncil/idmp/blob/57ef7480b0077090bec5df07eb1d589f07a1500d/ISO/ISO11238-Substances.rdf#L276-L280

which can be inherited from its other restriction:

https://github.com/edmcouncil/idmp/blob/57ef7480b0077090bec5df07eb1d589f07a1500d/ISO/ISO11238-Substances.rdf#L269-L273

This was revealed by https://jenkins.edmcouncil.org/view/idmp/job/idmp/job/additional_hygiene_test_for_obsolete_restrictions/4/.

**Comment by mereolog** [comment]
After https://github.com/edmcouncil/idmp/pull/603 we have another type of obsoleteness.

https://github.com/edmcouncil/idmp/blob/9e9c9ca29c71c3b6adbf0c0067dd16d4c8e50840/ISO/ISO11238-Substances.rdf#L290-L294

can be inferred from

https://github.com/edmcouncil/idmp/blob/9e9c9ca29c71c3b6adbf0c0067dd16d4c8e50840/ISO/ISO11238-Substances.rdf#L269-L273

**Comment by ElisaKendall** [comment]
The resolution to this issue was merged via pull request #603
