### ISSUE TITLE
Punning of idmp-spor:SPOR-Domain

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#629]
idmp-spor:SPOR-Domain is declared as an OWL class, but it is also an object in a triple with an object type property.

https://github.com/edmcouncil/idmp/blob/a2b9a712abcaae3f17f6dd65a84e95fa79b5bc69/ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf#L270-L276

**Comment by ElisaKendall** [comment]
@merelog -- where is it used an object in a triple with an object type property? There is a property called hasSPORDomain, but the class is enumerated ...

**Comment by mereolog** [comment]
It is line 275 in the snip above.

**Comment by ElisaKendall** [comment]
@mereolog Ah - ok, got it. I'll take care of this, thanks!

**Comment by ElisaKendall** [comment]
This issue should be closed to the resolution of pull request #632
