### ISSUE TITLE
Reflexive triples

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#636]
There are three "reflexive" triples in the IDMPO:

subject | property | object
| --- | --- | --- |
idmp-spor:SPOR-DataClassification-Public | idmp-spor:hasSPORVisibility | idmp-spor:SPOR-DataClassification-Public
idmp-spor:SPOR-Domain-HumanAndVeterinaryUse | idmp-spor:hasSPORDomain | idmp-spor:SPOR-Domain-HumanAndVeterinaryUse
idmp-spor:SPOR-RecordStatus-Current | idmp-spor:hasSPORStatus | idmp-spor:SPOR-RecordStatus-Current

Is this a correct conceptualisation of SPOR?

**Comment by ElisaKendall** [comment]
@mereolog yes -- that is precisely how it is defined (unfortunately)
